services:
  postgres:
    image: postgres:17

    container_name: governance_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: governance_admin
      POSTGRES_PASSWORD: governance_password
      POSTGRES_DB: enterprise_governance

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: