"""create database

Revision ID: 016d46bca61d
Revises: e65e6d75a6d4
Create Date: 2026-08-17 14:28:00.255990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016d46bca61d'
down_revision: Union[str, Sequence[str], None] = 'e65e6d75a6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database',
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('source_system_id', sa.UUID(), nullable=False),
    sa.Column('database_name', sa.String(length=150), nullable=False),
    sa.Column('database_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_system.source_system_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('source_system_id', 'database_name', name='uq_database_source_system_name')
    )
    op.create_index('idx_database_name', 'database', ['database_name'], unique=False)
    op.create_index('idx_database_type', 'database', ['database_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_database_type', table_name='database')
    op.drop_index('idx_database_name', table_name='database')
    op.drop_table('database')
    # ### end Alembic commands ###
