"""create lineage transformation

Revision ID: 042f36c0fcb4
Revises: f7b06a6d8fc1
Create Date: 2026-09-05 14:07:44.359382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042f36c0fcb4'
down_revision: Union[str, Sequence[str], None] = 'f7b06a6d8fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineage_transformation',
    sa.Column('lineage_transformation_id', sa.UUID(), nullable=False),
    sa.Column('lineage_flow_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('transformation_name', sa.String(length=255), nullable=False),
    sa.Column('transformation_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['lineage_flow_id'], ['lineage_flow.lineage_flow_id'], ),
    sa.PrimaryKeyConstraint('lineage_transformation_id'),
    sa.UniqueConstraint('lineage_flow_id', 'sequence_number', name='uq_lineage_transformation_flow_sequence')
    )
    op.create_index('idx_lineage_transformation_flow', 'lineage_transformation', ['lineage_flow_id'], unique=False)
    op.create_index('idx_lineage_transformation_sequence', 'lineage_transformation', ['sequence_number'], unique=False)
    op.create_index('idx_lineage_transformation_status', 'lineage_transformation', ['status'], unique=False)
    op.create_index('idx_lineage_transformation_type', 'lineage_transformation', ['transformation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lineage_transformation_type', table_name='lineage_transformation')
    op.drop_index('idx_lineage_transformation_status', table_name='lineage_transformation')
    op.drop_index('idx_lineage_transformation_sequence', table_name='lineage_transformation')
    op.drop_index('idx_lineage_transformation_flow', table_name='lineage_transformation')
    op.drop_table('lineage_transformation')
    # ### end Alembic commands ###
