"""create lineage source

Revision ID: 1fd4c6984cb4
Revises: 9e41c71eb4a6
Create Date: 2026-09-03 07:53:30.430120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd4c6984cb4'
down_revision: Union[str, Sequence[str], None] = '9e41c71eb4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineage_source',
    sa.Column('lineage_source_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('system_name', sa.String(length=150), nullable=False),
    sa.Column('business_domain', sa.String(length=150), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.PrimaryKeyConstraint('lineage_source_id'),
    sa.UniqueConstraint('source_name', 'system_name', name='uq_lineage_source_name_system')
    )
    op.create_index('idx_lineage_source_name', 'lineage_source', ['source_name'], unique=False)
    op.create_index('idx_lineage_source_status', 'lineage_source', ['status'], unique=False)
    op.create_index('idx_lineage_source_system', 'lineage_source', ['system_name'], unique=False)
    op.create_index('idx_lineage_source_type', 'lineage_source', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lineage_source_type', table_name='lineage_source')
    op.drop_index('idx_lineage_source_system', table_name='lineage_source')
    op.drop_index('idx_lineage_source_status', table_name='lineage_source')
    op.drop_index('idx_lineage_source_name', table_name='lineage_source')
    op.drop_table('lineage_source')
    # ### end Alembic commands ###
