"""create rule category and rule type

Revision ID: 20bb4f730956
Revises: bf1ab5ccdf2a
Create Date: 2026-08-26 14:44:17.201280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bb4f730956'
down_revision: Union[str, Sequence[str], None] = 'bf1ab5ccdf2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_category',
    sa.Column('rule_category_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('steward', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.PrimaryKeyConstraint('rule_category_id'),
    sa.UniqueConstraint('category_name', name='uq_rule_category_name')
    )
    op.create_index('idx_rule_category_name', 'rule_category', ['category_name'], unique=False)
    op.create_index('idx_rule_category_owner', 'rule_category', ['owner'], unique=False)
    op.create_index('idx_rule_category_status', 'rule_category', ['status'], unique=False)
    op.create_table('rule_type',
    sa.Column('rule_type_id', sa.UUID(), nullable=False),
    sa.Column('rule_type_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('execution_engine', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.PrimaryKeyConstraint('rule_type_id'),
    sa.UniqueConstraint('rule_type_name', name='uq_rule_type_name')
    )
    op.create_index('idx_rule_type_name', 'rule_type', ['rule_type_name'], unique=False)
    op.create_index('idx_rule_type_status', 'rule_type', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rule_type_status', table_name='rule_type')
    op.drop_index('idx_rule_type_name', table_name='rule_type')
    op.drop_table('rule_type')
    op.drop_index('idx_rule_category_status', table_name='rule_category')
    op.drop_index('idx_rule_category_owner', table_name='rule_category')
    op.drop_index('idx_rule_category_name', table_name='rule_category')
    op.drop_table('rule_category')
    # ### end Alembic commands ###
