"""create impact analysis

Revision ID: 25f927618c4b
Revises: 9a792fae7ed7
Create Date: 2026-09-05 14:21:53.965016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f927618c4b'
down_revision: Union[str, Sequence[str], None] = '9a792fae7ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_analysis',
    sa.Column('impact_analysis_id', sa.UUID(), nullable=False),
    sa.Column('lineage_mapping_id', sa.UUID(), nullable=False),
    sa.Column('analysis_number', sa.String(length=50), nullable=False),
    sa.Column('source_asset', sa.String(length=255), nullable=False),
    sa.Column('impact_scope', sa.String(length=100), nullable=False),
    sa.Column('affected_objects', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['lineage_mapping_id'], ['lineage_mapping.lineage_mapping_id'], ),
    sa.PrimaryKeyConstraint('impact_analysis_id'),
    sa.UniqueConstraint('analysis_number', name='uq_impact_analysis_number')
    )
    op.create_index('idx_impact_analysis_date', 'impact_analysis', ['analysis_date'], unique=False)
    op.create_index('idx_impact_analysis_number', 'impact_analysis', ['analysis_number'], unique=False)
    op.create_index('idx_impact_analysis_scope', 'impact_analysis', ['impact_scope'], unique=False)
    op.create_index('idx_impact_analysis_status', 'impact_analysis', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_impact_analysis_status', table_name='impact_analysis')
    op.drop_index('idx_impact_analysis_scope', table_name='impact_analysis')
    op.drop_index('idx_impact_analysis_number', table_name='impact_analysis')
    op.drop_index('idx_impact_analysis_date', table_name='impact_analysis')
    op.drop_table('impact_analysis')
    # ### end Alembic commands ###
