"""create data quality assessment

Revision ID: 2ee5cf35e17a
Revises: c62081edd60c
Create Date: 2026-09-02 15:34:09.773263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee5cf35e17a'
down_revision: Union[str, Sequence[str], None] = 'c62081edd60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_assessment',
    sa.Column('data_quality_assessment_id', sa.UUID(), nullable=False),
    sa.Column('data_quality_rule_id', sa.UUID(), nullable=False),
    sa.Column('assessment_number', sa.String(length=50), nullable=False),
    sa.Column('assessment_name', sa.String(length=255), nullable=False),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('execution_start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('execution_end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('executed_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['data_quality_rule_id'], ['data_quality_rule.data_quality_rule_id'], ),
    sa.PrimaryKeyConstraint('data_quality_assessment_id'),
    sa.UniqueConstraint('assessment_number', name='uq_dq_assessment_number')
    )
    op.create_index('idx_dq_assessment_number', 'data_quality_assessment', ['assessment_number'], unique=False)
    op.create_index('idx_dq_assessment_rule', 'data_quality_assessment', ['data_quality_rule_id'], unique=False)
    op.create_index('idx_dq_assessment_start_time', 'data_quality_assessment', ['execution_start_time'], unique=False)
    op.create_index('idx_dq_assessment_status', 'data_quality_assessment', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dq_assessment_status', table_name='data_quality_assessment')
    op.drop_index('idx_dq_assessment_start_time', table_name='data_quality_assessment')
    op.drop_index('idx_dq_assessment_rule', table_name='data_quality_assessment')
    op.drop_index('idx_dq_assessment_number', table_name='data_quality_assessment')
    op.drop_table('data_quality_assessment')
    # ### end Alembic commands ###
