"""create business glossary

Revision ID: 2feab630255a
Revises: d11b318bfcc5
Create Date: 2026-08-26 12:03:06.093278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2feab630255a'
down_revision: Union[str, Sequence[str], None] = 'd11b318bfcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_glossary',
    sa.Column('business_glossary_id', sa.UUID(), nullable=False),
    sa.Column('glossary_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('steward', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.PrimaryKeyConstraint('business_glossary_id'),
    sa.UniqueConstraint('glossary_name', name='uq_business_glossary_name')
    )
    op.create_index('idx_glossary_name', 'business_glossary', ['glossary_name'], unique=False)
    op.create_index('idx_glossary_owner', 'business_glossary', ['owner'], unique=False)
    op.create_index('idx_glossary_status', 'business_glossary', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_glossary_status', table_name='business_glossary')
    op.drop_index('idx_glossary_owner', table_name='business_glossary')
    op.drop_index('idx_glossary_name', table_name='business_glossary')
    op.drop_table('business_glossary')
    # ### end Alembic commands ###
