"""create data quality issue

Revision ID: 342b1ccc2068
Revises: 25d007f0759a
Create Date: 2026-09-03 07:40:22.181339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342b1ccc2068'
down_revision: Union[str, Sequence[str], None] = '25d007f0759a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_issue',
    sa.Column('data_quality_issue_id', sa.UUID(), nullable=False),
    sa.Column('data_quality_result_id', sa.UUID(), nullable=False),
    sa.Column('issue_number', sa.String(length=50), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('detected_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['data_quality_result_id'], ['data_quality_result.data_quality_result_id'], ),
    sa.PrimaryKeyConstraint('data_quality_issue_id'),
    sa.UniqueConstraint('issue_number', name='uq_dq_issue_number')
    )
    op.create_index('idx_dq_issue_number', 'data_quality_issue', ['issue_number'], unique=False)
    op.create_index('idx_dq_issue_owner', 'data_quality_issue', ['owner'], unique=False)
    op.create_index('idx_dq_issue_severity', 'data_quality_issue', ['severity'], unique=False)
    op.create_index('idx_dq_issue_status', 'data_quality_issue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dq_issue_status', table_name='data_quality_issue')
    op.drop_index('idx_dq_issue_severity', table_name='data_quality_issue')
    op.drop_index('idx_dq_issue_owner', table_name='data_quality_issue')
    op.drop_index('idx_dq_issue_number', table_name='data_quality_issue')
    op.drop_table('data_quality_issue')
    # ### end Alembic commands ###
