"""create lineage version

Revision ID: 35adef90b56f
Revises: 25f927618c4b
Create Date: 2026-09-05 14:25:24.849008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35adef90b56f'
down_revision: Union[str, Sequence[str], None] = '25f927618c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineage_version',
    sa.Column('lineage_version_id', sa.UUID(), nullable=False),
    sa.Column('lineage_flow_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['lineage_flow_id'], ['lineage_flow.lineage_flow_id'], ),
    sa.PrimaryKeyConstraint('lineage_version_id'),
    sa.UniqueConstraint('lineage_flow_id', 'version_number', name='uq_lineage_version_flow_version')
    )
    op.create_index('idx_lineage_version_flow', 'lineage_version', ['lineage_flow_id'], unique=False)
    op.create_index('idx_lineage_version_number', 'lineage_version', ['version_number'], unique=False)
    op.create_index('idx_lineage_version_status', 'lineage_version', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lineage_version_status', table_name='lineage_version')
    op.drop_index('idx_lineage_version_number', table_name='lineage_version')
    op.drop_index('idx_lineage_version_flow', table_name='lineage_version')
    op.drop_table('lineage_version')
    # ### end Alembic commands ###
