"""create database table

Revision ID: 3612cea475b7
Revises: 629dd9af1ed7
Create Date: 2026-08-18 15:53:55.220227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3612cea475b7'
down_revision: Union[str, Sequence[str], None] = '629dd9af1ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('database_table_id', sa.UUID(), nullable=False),
    sa.Column('database_schema_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('table_type', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['database_schema_id'], ['schema.database_schema_id'], ),
    sa.PrimaryKeyConstraint('database_table_id'),
    sa.UniqueConstraint('database_schema_id', 'table_name', name='uq_table_schema_name')
    )
    op.create_index('idx_table_classification', 'table', ['classification'], unique=False)
    op.create_index('idx_table_name', 'table', ['table_name'], unique=False)
    op.create_index('idx_table_status', 'table', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_table_status', table_name='table')
    op.drop_index('idx_table_name', table_name='table')
    op.drop_index('idx_table_classification', table_name='table')
    op.drop_table('table')
    # ### end Alembic commands ###
