"""create rule condition action version dependency execution context mapping

Revision ID: 45d5e5e0a55a
Revises: 8b3539847726
Create Date: 2026-08-27 15:24:23.536723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45d5e5e0a55a'
down_revision: Union[str, Sequence[str], None] = '8b3539847726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_action',
    sa.Column('rule_action_id', sa.UUID(), nullable=False),
    sa.Column('business_rule_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_rule_id'], ['business_rule.business_rule_id'], ),
    sa.PrimaryKeyConstraint('rule_action_id'),
    sa.UniqueConstraint('business_rule_id', 'sequence_number', name='uq_rule_action_rule_sequence')
    )
    op.create_index('idx_rule_action_rule', 'rule_action', ['business_rule_id'], unique=False)
    op.create_index('idx_rule_action_status', 'rule_action', ['status'], unique=False)
    op.create_index('idx_rule_action_type', 'rule_action', ['action_type'], unique=False)
    op.create_table('rule_condition',
    sa.Column('rule_condition_id', sa.UUID(), nullable=False),
    sa.Column('business_rule_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('left_operand', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('right_operand', sa.String(length=255), nullable=False),
    sa.Column('logical_operator', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_rule_id'], ['business_rule.business_rule_id'], ),
    sa.PrimaryKeyConstraint('rule_condition_id'),
    sa.UniqueConstraint('business_rule_id', 'sequence_number', name='uq_rule_condition_rule_sequence')
    )
    op.create_index('idx_rule_condition_rule', 'rule_condition', ['business_rule_id'], unique=False)
    op.create_index('idx_rule_condition_sequence', 'rule_condition', ['sequence_number'], unique=False)
    op.create_index('idx_rule_condition_status', 'rule_condition', ['status'], unique=False)
    op.create_table('rule_dependency',
    sa.Column('rule_dependency_id', sa.UUID(), nullable=False),
    sa.Column('parent_business_rule_id', sa.UUID(), nullable=False),
    sa.Column('dependent_business_rule_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['dependent_business_rule_id'], ['business_rule.business_rule_id'], ),
    sa.ForeignKeyConstraint(['parent_business_rule_id'], ['business_rule.business_rule_id'], ),
    sa.PrimaryKeyConstraint('rule_dependency_id'),
    sa.UniqueConstraint('parent_business_rule_id', 'dependent_business_rule_id', name='uq_rule_dependency_parent_dependent')
    )
    op.create_index('idx_rule_dependency_child', 'rule_dependency', ['dependent_business_rule_id'], unique=False)
    op.create_index('idx_rule_dependency_parent', 'rule_dependency', ['parent_business_rule_id'], unique=False)
    op.create_index('idx_rule_dependency_status', 'rule_dependency', ['status'], unique=False)
    op.create_table('rule_execution_context',
    sa.Column('rule_execution_context_id', sa.UUID(), nullable=False),
    sa.Column('business_rule_id', sa.UUID(), nullable=False),
    sa.Column('context_name', sa.String(length=100), nullable=False),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('execution_frequency', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_rule_id'], ['business_rule.business_rule_id'], ),
    sa.PrimaryKeyConstraint('rule_execution_context_id'),
    sa.UniqueConstraint('business_rule_id', 'context_name', name='uq_execution_context_rule_name')
    )
    op.create_index('idx_execution_context_name', 'rule_execution_context', ['context_name'], unique=False)
    op.create_index('idx_execution_context_rule', 'rule_execution_context', ['business_rule_id'], unique=False)
    op.create_index('idx_execution_context_status', 'rule_execution_context', ['status'], unique=False)
    op.create_table('rule_mapping',
    sa.Column('rule_mapping_id', sa.UUID(), nullable=False),
    sa.Column('business_rule_id', sa.UUID(), nullable=False),
    sa.Column('target_object_type', sa.String(length=50), nullable=False),
    sa.Column('target_object_identifier', sa.UUID(), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_rule_id'], ['business_rule.business_rule_id'], ),
    sa.PrimaryKeyConstraint('rule_mapping_id'),
    sa.UniqueConstraint('business_rule_id', 'target_object_type', 'target_object_identifier', name='uq_rule_mapping_rule_target')
    )
    op.create_index('idx_rule_mapping_rule', 'rule_mapping', ['business_rule_id'], unique=False)
    op.create_index('idx_rule_mapping_status', 'rule_mapping', ['status'], unique=False)
    op.create_index('idx_rule_mapping_target', 'rule_mapping', ['target_object_identifier'], unique=False)
    op.create_index('idx_rule_mapping_type', 'rule_mapping', ['target_object_type'], unique=False)
    op.create_table('rule_version',
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('business_rule_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('approved_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_rule_id'], ['business_rule.business_rule_id'], ),
    sa.PrimaryKeyConstraint('rule_version_id'),
    sa.UniqueConstraint('business_rule_id', 'version_number', name='uq_rule_version_rule_version')
    )
    op.create_index('idx_rule_version_number', 'rule_version', ['version_number'], unique=False)
    op.create_index('idx_rule_version_rule', 'rule_version', ['business_rule_id'], unique=False)
    op.create_index('idx_rule_version_status', 'rule_version', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rule_version_status', table_name='rule_version')
    op.drop_index('idx_rule_version_rule', table_name='rule_version')
    op.drop_index('idx_rule_version_number', table_name='rule_version')
    op.drop_table('rule_version')
    op.drop_index('idx_rule_mapping_type', table_name='rule_mapping')
    op.drop_index('idx_rule_mapping_target', table_name='rule_mapping')
    op.drop_index('idx_rule_mapping_status', table_name='rule_mapping')
    op.drop_index('idx_rule_mapping_rule', table_name='rule_mapping')
    op.drop_table('rule_mapping')
    op.drop_index('idx_execution_context_status', table_name='rule_execution_context')
    op.drop_index('idx_execution_context_rule', table_name='rule_execution_context')
    op.drop_index('idx_execution_context_name', table_name='rule_execution_context')
    op.drop_table('rule_execution_context')
    op.drop_index('idx_rule_dependency_status', table_name='rule_dependency')
    op.drop_index('idx_rule_dependency_parent', table_name='rule_dependency')
    op.drop_index('idx_rule_dependency_child', table_name='rule_dependency')
    op.drop_table('rule_dependency')
    op.drop_index('idx_rule_condition_status', table_name='rule_condition')
    op.drop_index('idx_rule_condition_sequence', table_name='rule_condition')
    op.drop_index('idx_rule_condition_rule', table_name='rule_condition')
    op.drop_table('rule_condition')
    op.drop_index('idx_rule_action_type', table_name='rule_action')
    op.drop_index('idx_rule_action_status', table_name='rule_action')
    op.drop_index('idx_rule_action_rule', table_name='rule_action')
    op.drop_table('rule_action')
    # ### end Alembic commands ###
