"""create database schema

Revision ID: 629dd9af1ed7
Revises: 016d46bca61d
Create Date: 2026-08-17 17:27:15.059500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629dd9af1ed7'
down_revision: Union[str, Sequence[str], None] = '016d46bca61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema',
    sa.Column('database_schema_id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('schema_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['database.database_id'], ),
    sa.PrimaryKeyConstraint('database_schema_id'),
    sa.UniqueConstraint('database_id', 'schema_name', name='uq_schema_database_name')
    )
    op.create_index('idx_schema_database', 'schema', ['database_id'], unique=False)
    op.create_index('idx_schema_name', 'schema', ['schema_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_schema_name', table_name='schema')
    op.drop_index('idx_schema_database', table_name='schema')
    op.drop_table('schema')
    # ### end Alembic commands ###
