"""create table column

Revision ID: 6da871e5e4ff
Revises: 3612cea475b7
Create Date: 2026-08-18 16:01:21.419355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da871e5e4ff'
down_revision: Union[str, Sequence[str], None] = '3612cea475b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column',
    sa.Column('table_column_id', sa.UUID(), nullable=False),
    sa.Column('database_table_id', sa.UUID(), nullable=False),
    sa.Column('column_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logical_data_type', sa.String(length=50), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('primary_key_flag', sa.Boolean(), nullable=False),
    sa.Column('foreign_key_flag', sa.Boolean(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('critical_data_element_flag', sa.Boolean(), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['database_table_id'], ['table.database_table_id'], ),
    sa.PrimaryKeyConstraint('table_column_id'),
    sa.UniqueConstraint('database_table_id', 'column_name', name='uq_column_table_name')
    )
    op.create_index('idx_column_cde', 'column', ['critical_data_element_flag'], unique=False)
    op.create_index('idx_column_datatype', 'column', ['logical_data_type'], unique=False)
    op.create_index('idx_column_name', 'column', ['column_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_column_name', table_name='column')
    op.drop_index('idx_column_datatype', table_name='column')
    op.drop_index('idx_column_cde', table_name='column')
    op.drop_table('column')
    # ### end Alembic commands ###
