"""create business term relationship

Revision ID: 8b3539847726
Revises: ed60600dd4ee
Create Date: 2026-08-27 15:12:20.060525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3539847726'
down_revision: Union[str, Sequence[str], None] = 'ed60600dd4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_term_relationship',
    sa.Column('business_term_relationship_id', sa.UUID(), nullable=False),
    sa.Column('source_business_term_id', sa.UUID(), nullable=False),
    sa.Column('target_business_term_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['source_business_term_id'], ['business_term.business_term_id'], ),
    sa.ForeignKeyConstraint(['target_business_term_id'], ['business_term.business_term_id'], ),
    sa.PrimaryKeyConstraint('business_term_relationship_id'),
    sa.UniqueConstraint('source_business_term_id', 'relationship_type', 'target_business_term_id', name='uq_term_relationship_source_type_target')
    )
    op.create_index('idx_relationship_source', 'business_term_relationship', ['source_business_term_id'], unique=False)
    op.create_index('idx_relationship_status', 'business_term_relationship', ['status'], unique=False)
    op.create_index('idx_relationship_target', 'business_term_relationship', ['target_business_term_id'], unique=False)
    op.create_index('idx_relationship_type', 'business_term_relationship', ['relationship_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_relationship_type', table_name='business_term_relationship')
    op.drop_index('idx_relationship_target', table_name='business_term_relationship')
    op.drop_index('idx_relationship_status', table_name='business_term_relationship')
    op.drop_index('idx_relationship_source', table_name='business_term_relationship')
    op.drop_table('business_term_relationship')
    # ### end Alembic commands ###
