"""create data quality dimension

Revision ID: 923a1d298733
Revises: 45d5e5e0a55a
Create Date: 2026-09-02 12:14:34.565439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923a1d298733'
down_revision: Union[str, Sequence[str], None] = '45d5e5e0a55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_dimension',
    sa.Column('data_quality_dimension_id', sa.UUID(), nullable=False),
    sa.Column('dimension_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.PrimaryKeyConstraint('data_quality_dimension_id'),
    sa.UniqueConstraint('dimension_name', name='uq_dq_dimension_name')
    )
    op.create_index('idx_dq_dimension_name', 'data_quality_dimension', ['dimension_name'], unique=False)
    op.create_index('idx_dq_dimension_owner', 'data_quality_dimension', ['owner'], unique=False)
    op.create_index('idx_dq_dimension_status', 'data_quality_dimension', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dq_dimension_status', table_name='data_quality_dimension')
    op.drop_index('idx_dq_dimension_owner', table_name='data_quality_dimension')
    op.drop_index('idx_dq_dimension_name', table_name='data_quality_dimension')
    op.drop_table('data_quality_dimension')
    # ### end Alembic commands ###
