"""create business rule

Revision ID: 92e2c553f3f4
Revises: 20bb4f730956
Create Date: 2026-08-27 15:05:58.106595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e2c553f3f4'
down_revision: Union[str, Sequence[str], None] = '20bb4f730956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_rule',
    sa.Column('business_rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_category_id', sa.UUID(), nullable=False),
    sa.Column('rule_type_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('steward', sa.String(length=100), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['rule_category_id'], ['rule_category.rule_category_id'], ),
    sa.ForeignKeyConstraint(['rule_type_id'], ['rule_type.rule_type_id'], ),
    sa.PrimaryKeyConstraint('business_rule_id'),
    sa.UniqueConstraint('rule_code', name='uq_business_rule_code')
    )
    op.create_index('idx_business_rule_code', 'business_rule', ['rule_code'], unique=False)
    op.create_index('idx_business_rule_name', 'business_rule', ['rule_name'], unique=False)
    op.create_index('idx_business_rule_owner', 'business_rule', ['owner'], unique=False)
    op.create_index('idx_business_rule_priority', 'business_rule', ['priority'], unique=False)
    op.create_index('idx_business_rule_status', 'business_rule', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_business_rule_status', table_name='business_rule')
    op.drop_index('idx_business_rule_priority', table_name='business_rule')
    op.drop_index('idx_business_rule_owner', table_name='business_rule')
    op.drop_index('idx_business_rule_name', table_name='business_rule')
    op.drop_index('idx_business_rule_code', table_name='business_rule')
    op.drop_table('business_rule')
    # ### end Alembic commands ###
