"""create lineage mapping

Revision ID: 9a792fae7ed7
Revises: 042f36c0fcb4
Create Date: 2026-09-05 14:11:12.485826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a792fae7ed7'
down_revision: Union[str, Sequence[str], None] = '042f36c0fcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineage_mapping',
    sa.Column('lineage_mapping_id', sa.UUID(), nullable=False),
    sa.Column('lineage_flow_id', sa.UUID(), nullable=False),
    sa.Column('lineage_transformation_id', sa.UUID(), nullable=True),
    sa.Column('source_attribute', sa.String(length=255), nullable=False),
    sa.Column('target_attribute', sa.String(length=255), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['lineage_flow_id'], ['lineage_flow.lineage_flow_id'], ),
    sa.ForeignKeyConstraint(['lineage_transformation_id'], ['lineage_transformation.lineage_transformation_id'], ),
    sa.PrimaryKeyConstraint('lineage_mapping_id'),
    sa.UniqueConstraint('lineage_flow_id', 'source_attribute', 'target_attribute', name='uq_lineage_mapping_flow_source_target')
    )
    op.create_index('idx_lineage_mapping_flow', 'lineage_mapping', ['lineage_flow_id'], unique=False)
    op.create_index('idx_lineage_mapping_source', 'lineage_mapping', ['source_attribute'], unique=False)
    op.create_index('idx_lineage_mapping_status', 'lineage_mapping', ['status'], unique=False)
    op.create_index('idx_lineage_mapping_target', 'lineage_mapping', ['target_attribute'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lineage_mapping_target', table_name='lineage_mapping')
    op.drop_index('idx_lineage_mapping_status', table_name='lineage_mapping')
    op.drop_index('idx_lineage_mapping_source', table_name='lineage_mapping')
    op.drop_index('idx_lineage_mapping_flow', table_name='lineage_mapping')
    op.drop_table('lineage_mapping')
    # ### end Alembic commands ###
