"""create lineage target

Revision ID: 9d6657445897
Revises: 1fd4c6984cb4
Create Date: 2026-09-05 13:32:21.467838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6657445897'
down_revision: Union[str, Sequence[str], None] = '1fd4c6984cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineage_target',
    sa.Column('lineage_target_id', sa.UUID(), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('system_name', sa.String(length=150), nullable=False),
    sa.Column('business_domain', sa.String(length=150), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.PrimaryKeyConstraint('lineage_target_id'),
    sa.UniqueConstraint('target_name', 'system_name', name='uq_lineage_target_name_system')
    )
    op.create_index('idx_lineage_target_name', 'lineage_target', ['target_name'], unique=False)
    op.create_index('idx_lineage_target_status', 'lineage_target', ['status'], unique=False)
    op.create_index('idx_lineage_target_system', 'lineage_target', ['system_name'], unique=False)
    op.create_index('idx_lineage_target_type', 'lineage_target', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lineage_target_type', table_name='lineage_target')
    op.drop_index('idx_lineage_target_system', table_name='lineage_target')
    op.drop_index('idx_lineage_target_status', table_name='lineage_target')
    op.drop_index('idx_lineage_target_name', table_name='lineage_target')
    op.drop_table('lineage_target')
    # ### end Alembic commands ###
