"""create data quality exception

Revision ID: 9e41c71eb4a6
Revises: 342b1ccc2068
Create Date: 2026-09-03 07:50:31.607907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e41c71eb4a6'
down_revision: Union[str, Sequence[str], None] = '342b1ccc2068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_exception',
    sa.Column('data_quality_exception_id', sa.UUID(), nullable=False),
    sa.Column('data_quality_issue_id', sa.UUID(), nullable=False),
    sa.Column('exception_number', sa.String(length=50), nullable=False),
    sa.Column('exception_reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('approval_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['data_quality_issue_id'], ['data_quality_issue.data_quality_issue_id'], ),
    sa.PrimaryKeyConstraint('data_quality_exception_id'),
    sa.UniqueConstraint('exception_number', name='uq_dq_exception_number')
    )
    op.create_index('idx_dq_exception_expiry', 'data_quality_exception', ['expiry_date'], unique=False)
    op.create_index('idx_dq_exception_number', 'data_quality_exception', ['exception_number'], unique=False)
    op.create_index('idx_dq_exception_status', 'data_quality_exception', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dq_exception_status', table_name='data_quality_exception')
    op.drop_index('idx_dq_exception_number', table_name='data_quality_exception')
    op.drop_index('idx_dq_exception_expiry', table_name='data_quality_exception')
    op.drop_table('data_quality_exception')
    # ### end Alembic commands ###
