"""create lineage snapshot

Revision ID: afddcea9037e
Revises: 35adef90b56f
Create Date: 2026-09-05 14:30:59.333940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afddcea9037e'
down_revision: Union[str, Sequence[str], None] = '35adef90b56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineage_snapshot',
    sa.Column('lineage_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('lineage_flow_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_name', sa.String(length=255), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['lineage_flow_id'], ['lineage_flow.lineage_flow_id'], ),
    sa.PrimaryKeyConstraint('lineage_snapshot_id'),
    sa.UniqueConstraint('lineage_flow_id', 'snapshot_name', name='uq_lineage_snapshot_flow_name')
    )
    op.create_index('idx_lineage_snapshot_date', 'lineage_snapshot', ['snapshot_date'], unique=False)
    op.create_index('idx_lineage_snapshot_flow', 'lineage_snapshot', ['lineage_flow_id'], unique=False)
    op.create_index('idx_lineage_snapshot_name', 'lineage_snapshot', ['snapshot_name'], unique=False)
    op.create_index('idx_lineage_snapshot_status', 'lineage_snapshot', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lineage_snapshot_status', table_name='lineage_snapshot')
    op.drop_index('idx_lineage_snapshot_name', table_name='lineage_snapshot')
    op.drop_index('idx_lineage_snapshot_flow', table_name='lineage_snapshot')
    op.drop_index('idx_lineage_snapshot_date', table_name='lineage_snapshot')
    op.drop_table('lineage_snapshot')
    # ### end Alembic commands ###
