"""create business definition acronym synonym

Revision ID: bf1ab5ccdf2a
Revises: c0e77389503d
Create Date: 2026-08-26 12:18:45.280444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1ab5ccdf2a'
down_revision: Union[str, Sequence[str], None] = 'c0e77389503d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acronym',
    sa.Column('acronym_id', sa.UUID(), nullable=False),
    sa.Column('business_term_id', sa.UUID(), nullable=False),
    sa.Column('acronym', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_term_id'], ['business_term.business_term_id'], ),
    sa.PrimaryKeyConstraint('acronym_id'),
    sa.UniqueConstraint('acronym', name='uq_acronym')
    )
    op.create_index('idx_acronym', 'acronym', ['acronym'], unique=False)
    op.create_index('idx_acronym_status', 'acronym', ['status'], unique=False)
    op.create_table('business_definition',
    sa.Column('business_definition_id', sa.UUID(), nullable=False),
    sa.Column('business_term_id', sa.UUID(), nullable=False),
    sa.Column('definition_text', sa.Text(), nullable=False),
    sa.Column('definition_source', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('approved_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_term_id'], ['business_term.business_term_id'], ),
    sa.PrimaryKeyConstraint('business_definition_id')
    )
    op.create_index('idx_definition_status', 'business_definition', ['status'], unique=False)
    op.create_index('idx_definition_term', 'business_definition', ['business_term_id'], unique=False)
    op.create_index('idx_definition_version', 'business_definition', ['version'], unique=False)
    op.create_table('synonym',
    sa.Column('synonym_id', sa.UUID(), nullable=False),
    sa.Column('business_term_id', sa.UUID(), nullable=False),
    sa.Column('synonym', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_term_id'], ['business_term.business_term_id'], ),
    sa.PrimaryKeyConstraint('synonym_id')
    )
    op.create_index('idx_synonym', 'synonym', ['synonym'], unique=False)
    op.create_index('idx_synonym_status', 'synonym', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_synonym_status', table_name='synonym')
    op.drop_index('idx_synonym', table_name='synonym')
    op.drop_table('synonym')
    op.drop_index('idx_definition_version', table_name='business_definition')
    op.drop_index('idx_definition_term', table_name='business_definition')
    op.drop_index('idx_definition_status', table_name='business_definition')
    op.drop_table('business_definition')
    op.drop_index('idx_acronym_status', table_name='acronym')
    op.drop_index('idx_acronym', table_name='acronym')
    op.drop_table('acronym')
    # ### end Alembic commands ###
