"""create business term

Revision ID: c0e77389503d
Revises: c72c7b5269c9
Create Date: 2026-08-26 12:14:51.959150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e77389503d'
down_revision: Union[str, Sequence[str], None] = 'c72c7b5269c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_term',
    sa.Column('business_term_id', sa.UUID(), nullable=False),
    sa.Column('business_category_id', sa.UUID(), nullable=False),
    sa.Column('business_term_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('preferred_definition', sa.Text(), nullable=False),
    sa.Column('business_domain', sa.String(length=100), nullable=False),
    sa.Column('business_capability', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('steward', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_category_id'], ['business_category.business_category_id'], ),
    sa.PrimaryKeyConstraint('business_term_id'),
    sa.UniqueConstraint('business_category_id', 'business_term_name', name='uq_business_term_category_name')
    )
    op.create_index('idx_business_domain', 'business_term', ['business_domain'], unique=False)
    op.create_index('idx_business_term_name', 'business_term', ['business_term_name'], unique=False)
    op.create_index('idx_business_term_owner', 'business_term', ['owner'], unique=False)
    op.create_index('idx_business_term_status', 'business_term', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_business_term_status', table_name='business_term')
    op.drop_index('idx_business_term_owner', table_name='business_term')
    op.drop_index('idx_business_term_name', table_name='business_term')
    op.drop_index('idx_business_domain', table_name='business_term')
    op.drop_table('business_term')
    # ### end Alembic commands ###
