"""create database view

Revision ID: c1e2cd64a9cf
Revises: 6da871e5e4ff
Create Date: 2026-08-22 08:14:05.481150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e2cd64a9cf'
down_revision: Union[str, Sequence[str], None] = '6da871e5e4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_view',
    sa.Column('database_view_id', sa.UUID(), nullable=False),
    sa.Column('database_schema_id', sa.UUID(), nullable=False),
    sa.Column('view_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('view_type', sa.String(length=50), nullable=False),
    sa.Column('sql_definition', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['database_schema_id'], ['schema.database_schema_id'], ),
    sa.PrimaryKeyConstraint('database_view_id'),
    sa.UniqueConstraint('database_schema_id', 'view_name', name='uq_view_schema_name')
    )
    op.create_index('idx_view_name', 'database_view', ['view_name'], unique=False)
    op.create_index('idx_view_status', 'database_view', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_view_status', table_name='database_view')
    op.drop_index('idx_view_name', table_name='database_view')
    op.drop_table('database_view')
    # ### end Alembic commands ###
