"""create data quality rule

Revision ID: c62081edd60c
Revises: 923a1d298733
Create Date: 2026-09-02 14:42:40.979785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62081edd60c'
down_revision: Union[str, Sequence[str], None] = '923a1d298733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_rule',
    sa.Column('data_quality_rule_id', sa.UUID(), nullable=False),
    sa.Column('data_quality_dimension_id', sa.UUID(), nullable=False),
    sa.Column('business_rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('target_data_asset_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('threshold_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('execution_frequency', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_rule_id'], ['business_rule.business_rule_id'], ),
    sa.ForeignKeyConstraint(['data_quality_dimension_id'], ['data_quality_dimension.data_quality_dimension_id'], ),
    sa.PrimaryKeyConstraint('data_quality_rule_id'),
    sa.UniqueConstraint('rule_code', name='uq_dq_rule_code')
    )
    op.create_index('idx_dq_rule_code', 'data_quality_rule', ['rule_code'], unique=False)
    op.create_index('idx_dq_rule_dimension', 'data_quality_rule', ['data_quality_dimension_id'], unique=False)
    op.create_index('idx_dq_rule_owner', 'data_quality_rule', ['owner'], unique=False)
    op.create_index('idx_dq_rule_status', 'data_quality_rule', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dq_rule_status', table_name='data_quality_rule')
    op.drop_index('idx_dq_rule_owner', table_name='data_quality_rule')
    op.drop_index('idx_dq_rule_dimension', table_name='data_quality_rule')
    op.drop_index('idx_dq_rule_code', table_name='data_quality_rule')
    op.drop_table('data_quality_rule')
    # ### end Alembic commands ###
