"""create business category

Revision ID: c72c7b5269c9
Revises: 2feab630255a
Create Date: 2026-08-26 12:09:20.650852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72c7b5269c9'
down_revision: Union[str, Sequence[str], None] = '2feab630255a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_category',
    sa.Column('business_category_id', sa.UUID(), nullable=False),
    sa.Column('business_glossary_id', sa.UUID(), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('steward', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_glossary_id'], ['business_glossary.business_glossary_id'], ),
    sa.ForeignKeyConstraint(['parent_category_id'], ['business_category.business_category_id'], ),
    sa.PrimaryKeyConstraint('business_category_id'),
    sa.UniqueConstraint('business_glossary_id', 'category_name', name='uq_business_category_glossary_name')
    )
    op.create_index('idx_category_name', 'business_category', ['category_name'], unique=False)
    op.create_index('idx_category_owner', 'business_category', ['owner'], unique=False)
    op.create_index('idx_category_status', 'business_category', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_category_status', table_name='business_category')
    op.drop_index('idx_category_owner', table_name='business_category')
    op.drop_index('idx_category_name', table_name='business_category')
    op.drop_table('business_category')
    # ### end Alembic commands ###
