"""create data asset

Revision ID: d11b318bfcc5
Revises: df4365b60d25
Create Date: 2026-08-23 12:13:01.267767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11b318bfcc5'
down_revision: Union[str, Sequence[str], None] = 'df4365b60d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_asset',
    sa.Column('data_asset_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('asset_identifier', sa.UUID(), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('steward', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('critical_data_element_flag', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('data_asset_id'),
    sa.UniqueConstraint('asset_type', 'asset_identifier', name='uq_asset_type_identifier')
    )
    op.create_index('idx_asset_classification', 'data_asset', ['classification'], unique=False)
    op.create_index('idx_asset_name', 'data_asset', ['asset_name'], unique=False)
    op.create_index('idx_asset_status', 'data_asset', ['status'], unique=False)
    op.create_index('idx_asset_type', 'data_asset', ['asset_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_asset_type', table_name='data_asset')
    op.drop_index('idx_asset_status', table_name='data_asset')
    op.drop_index('idx_asset_name', table_name='data_asset')
    op.drop_index('idx_asset_classification', table_name='data_asset')
    op.drop_table('data_asset')
    # ### end Alembic commands ###
