"""create api asset

Revision ID: df4365b60d25
Revises: e162416e8cce
Create Date: 2026-08-23 08:02:29.905655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4365b60d25'
down_revision: Union[str, Sequence[str], None] = 'e162416e8cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_asset',
    sa.Column('api_asset_id', sa.UUID(), nullable=False),
    sa.Column('source_system_id', sa.UUID(), nullable=False),
    sa.Column('api_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_type', sa.String(length=30), nullable=False),
    sa.Column('api_version', sa.String(length=30), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_system.source_system_id'], ),
    sa.PrimaryKeyConstraint('api_asset_id'),
    sa.UniqueConstraint('source_system_id', 'api_name', 'api_version', name='uq_api_source_system_name_version')
    )
    op.create_index('idx_api_name', 'api_asset', ['api_name'], unique=False)
    op.create_index('idx_api_status', 'api_asset', ['status'], unique=False)
    op.create_index('idx_api_type', 'api_asset', ['api_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_api_type', table_name='api_asset')
    op.drop_index('idx_api_status', table_name='api_asset')
    op.drop_index('idx_api_name', table_name='api_asset')
    op.drop_table('api_asset')
    # ### end Alembic commands ###
