"""create file asset

Revision ID: e162416e8cce
Revises: c1e2cd64a9cf
Create Date: 2026-08-23 07:53:20.791424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e162416e8cce'
down_revision: Union[str, Sequence[str], None] = 'c1e2cd64a9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_asset',
    sa.Column('file_asset_id', sa.UUID(), nullable=False),
    sa.Column('source_system_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_format', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_system.source_system_id'], ),
    sa.PrimaryKeyConstraint('file_asset_id'),
    sa.UniqueConstraint('source_system_id', 'file_name', name='uq_file_source_system_name')
    )
    op.create_index('idx_file_name', 'file_asset', ['file_name'], unique=False)
    op.create_index('idx_file_status', 'file_asset', ['status'], unique=False)
    op.create_index('idx_file_type', 'file_asset', ['file_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_type', table_name='file_asset')
    op.drop_index('idx_file_status', table_name='file_asset')
    op.drop_index('idx_file_name', table_name='file_asset')
    op.drop_table('file_asset')
    # ### end Alembic commands ###
