"""create source system

Revision ID: e65e6d75a6d4
Revises: 
Create Date: 2026-08-15 15:09:35.621782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65e6d75a6d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_system',
    sa.Column('source_system_id', sa.UUID(), nullable=False),
    sa.Column('system_code', sa.String(length=50), nullable=False),
    sa.Column('system_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_type', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('business_domain', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=30), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('steward', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('source_system_id'),
    sa.UniqueConstraint('system_code')
    )
    op.create_index('idx_source_system_domain', 'source_system', ['business_domain'], unique=False)
    op.create_index('idx_source_system_name', 'source_system', ['system_name'], unique=False)
    op.create_index('idx_source_system_status', 'source_system', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_source_system_status', table_name='source_system')
    op.drop_index('idx_source_system_name', table_name='source_system')
    op.drop_index('idx_source_system_domain', table_name='source_system')
    op.drop_table('source_system')
    # ### end Alembic commands ###
