"""create business rule association

Revision ID: ed60600dd4ee
Revises: 92e2c553f3f4
Create Date: 2026-08-27 15:10:07.224895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed60600dd4ee'
down_revision: Union[str, Sequence[str], None] = '92e2c553f3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_rule_association',
    sa.Column('business_rule_association_id', sa.UUID(), nullable=False),
    sa.Column('business_term_id', sa.UUID(), nullable=False),
    sa.Column('business_rule_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['business_rule_id'], ['business_rule.business_rule_id'], ),
    sa.ForeignKeyConstraint(['business_term_id'], ['business_term.business_term_id'], ),
    sa.PrimaryKeyConstraint('business_rule_association_id'),
    sa.UniqueConstraint('business_term_id', 'business_rule_id', name='uq_rule_association_term_rule')
    )
    op.create_index('idx_rule_association_rule', 'business_rule_association', ['business_rule_id'], unique=False)
    op.create_index('idx_rule_association_status', 'business_rule_association', ['status'], unique=False)
    op.create_index('idx_rule_association_term', 'business_rule_association', ['business_term_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rule_association_term', table_name='business_rule_association')
    op.drop_index('idx_rule_association_status', table_name='business_rule_association')
    op.drop_index('idx_rule_association_rule', table_name='business_rule_association')
    op.drop_table('business_rule_association')
    # ### end Alembic commands ###
