"""create lineage process and flow

Revision ID: f7b06a6d8fc1
Revises: 9d6657445897
Create Date: 2026-09-05 14:04:20.478687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b06a6d8fc1'
down_revision: Union[str, Sequence[str], None] = '9d6657445897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineage_process',
    sa.Column('lineage_process_id', sa.UUID(), nullable=False),
    sa.Column('process_name', sa.String(length=255), nullable=False),
    sa.Column('process_type', sa.String(length=100), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.PrimaryKeyConstraint('lineage_process_id'),
    sa.UniqueConstraint('process_name', name='uq_lineage_process_name')
    )
    op.create_index('idx_lineage_process_name', 'lineage_process', ['process_name'], unique=False)
    op.create_index('idx_lineage_process_status', 'lineage_process', ['status'], unique=False)
    op.create_index('idx_lineage_process_type', 'lineage_process', ['process_type'], unique=False)
    op.create_table('lineage_flow',
    sa.Column('lineage_flow_id', sa.UUID(), nullable=False),
    sa.Column('lineage_source_id', sa.UUID(), nullable=False),
    sa.Column('lineage_process_id', sa.UUID(), nullable=False),
    sa.Column('flow_name', sa.String(length=255), nullable=False),
    sa.Column('flow_type', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.ForeignKeyConstraint(['lineage_process_id'], ['lineage_process.lineage_process_id'], ),
    sa.ForeignKeyConstraint(['lineage_source_id'], ['lineage_source.lineage_source_id'], ),
    sa.PrimaryKeyConstraint('lineage_flow_id'),
    sa.UniqueConstraint('flow_name', name='uq_lineage_flow_name')
    )
    op.create_index('idx_lineage_flow_name', 'lineage_flow', ['flow_name'], unique=False)
    op.create_index('idx_lineage_flow_process', 'lineage_flow', ['lineage_process_id'], unique=False)
    op.create_index('idx_lineage_flow_source', 'lineage_flow', ['lineage_source_id'], unique=False)
    op.create_index('idx_lineage_flow_status', 'lineage_flow', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lineage_flow_status', table_name='lineage_flow')
    op.drop_index('idx_lineage_flow_source', table_name='lineage_flow')
    op.drop_index('idx_lineage_flow_process', table_name='lineage_flow')
    op.drop_index('idx_lineage_flow_name', table_name='lineage_flow')
    op.drop_table('lineage_flow')
    op.drop_index('idx_lineage_process_type', table_name='lineage_process')
    op.drop_index('idx_lineage_process_status', table_name='lineage_process')
    op.drop_index('idx_lineage_process_name', table_name='lineage_process')
    op.drop_table('lineage_process')
    # ### end Alembic commands ###
